Lch/modulo noticias
MinKruger/LabSoftBackEnd pull request #26
Opened 2021-10-19 11:03 UTC by LuskasDMC

2021-10-19 11:07 UTC, MinKruger requested changes
Ajustar o comentário feito do arquivo create-postagem.js

2021-10-19 11:07 UTC, MinKruger commented on src/data/useCases/postagem/create-postagem.js
> +      throw new BadRequestException("User not authorized");
Tem implementado uma UnauthorizedException, use ela quando for questão de não autorização

2021-10-19 20:13 UTC, LuskasDMC commented on src/data/useCases/postagem/create-postagem.js
> +      throw new BadRequestException("User not authorized");
na vdd nem um nem outro, o correto msm seria o Forbidden(403). Fiz a alteração.
![image](https://user-images.githubusercontent.com/43136700/137983225-df04ca97-534c-41d4-8a7c-424e3ee39747.png)

2021-10-19 22:34 UTC, andreefl approved these changes

2021-10-20 00:06 UTC, MinKruger approved these changes

2021-10-20 00:06 UTC, merged